model:
  n_layer: 2
  n_head: 2
  n_embd: 256
  linear: False

data:
  name: 'matrix'
  min_val: -1.0
  max_val: 1.0
  prec: 2
  m: 7
  n: 7
  r: 2
  p_mask: 0.3
  n_train: 256
  n_test: 256
  n_test: 64
  fixed_len: True

train:
  lr: 0.0001
  grad_clip: -1
  num_steps: 100000
  wandb: True
  save_ckpt: False
  ckpt_freq: 100
